language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - ./.install-htslib.sh

install:
  - sudo pip install cffi
  - sudo python setup.py develop

script:
  - python -c "import hts; hts.doctests()"
