language: python
python:
  - "2.7" 

install:
  - ./.install-htslib.sh
  - pip install cffi nose coverage coveralls
  - python setup.py develop

script:
  - coverage run --source=hts setup.py nosetests

after_success:
  - coveralls
